from pydantic import BaseModel, Field
from typing import List, Optional

class StrategyReport(BaseModel):
    hook_strategy: str = Field(..., description="Pattern Interrupt visual and verbal hook")
    body_strategy: str = Field(..., description="Value addition and retention strategy")
    cta_strategy: str = Field(..., description="Call to Action strategy")

class Scene(BaseModel):
    scene_number: int = Field(..., description="Sequential number of the scene (1 to 12)")
    timestamp: str = Field(..., description="Estimated timestamp for the scene, e.g., '00:00 - 00:05'")
    dialogue: str = Field(..., description="Voiceover dialogue or text on screen")
    visual_description: str = Field(..., description="Cinematic description of the scene")
    camera_instruction: str = Field(..., description="Camera movement and angle instructions")
    video_prompt: Optional[str] = Field(None, description="Hyper-detailed prompt generated by the Visual Director (70-100 words)")
    seed_id: Optional[str] = Field(None, description="Character Seed ID for visual consistency across scenes")
    video_path: Optional[str] = Field(None, description="Local path to the generated video asset")
    audio_path: Optional[str] = Field(None, description="Local path to the generated audio asset")

class Script(BaseModel):
    scenes: List[Scene] = Field(..., min_length=12, max_length=12, description="Exactly 12 scenes making up the 50-60 second video")

class QualityScore(BaseModel):
    continuity_score: int = Field(..., ge=1, le=10, description="Score from 1-10 for visual consistency and continuity")
    engagement_score: int = Field(..., ge=1, le=10, description="Score from 1-10 for retention potential")
    feedback: str = Field(..., description="Specific feedback on what needs to be improved if score < 8")

# Note: Pydantic State Schema for LangGraph
class AgencyState(BaseModel):
    niche_query: str = Field(..., description="User provided niche and hook idea")
    strategy: Optional[StrategyReport] = None
    script: Optional[Script] = None
    base_character_seed: Optional[str] = Field(None, description="Seed generated in Scene 1 to be reused throughout")
    final_video_path: Optional[str] = None
    score: Optional[QualityScore] = None
    refinement_iterations: int = 0
